# Build the Go Binary.
FROM golang:1.17 as build_test-api
ENV CGO_ENABLED 0
ARG BUILD_REF

# Copy the source code into the container.
COPY . /service

# Build the service binary.
WORKDIR /service/app/services/test-api
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.15
ARG BUILD_DATE
ARG BUILD_REF

RUN addgroup -g 1000 -S test && \
    adduser -u 1000 -h /service -G test -S test
COPY --from=build_test-api --chown=test:test /service/app/services/test-api/test-api /service/test-api
COPY --from=build_test-api --chown=test:test /service/config /service/config
WORKDIR /service
USER test
CMD ["./test-api"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="test-api" \
      org.opencontainers.image.authors="Icy37785 <icy37785@gmail.com>" \
      org.opencontainers.image.source="https://github.com/icy37785/go-frame/app/test-api" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Icy37785"
